### ISSUE TITLE
AITalkにparamを渡して、音声データ受け取る

### ISSUE THREAD

**Issue by kboy-silvergym** [antexe/season_rapper#5]

**Comment by shinji19** [comment]
curl -X POST \
  'http://webapi.aitalk.jp/webapi/v2/ttsget.php?username=「」&password=「」&text=%E3%81%93%E3%82%93%E3%81%AB%E3%81%A1%E3%81%AF&speaker_name=nozomi&ext=ogg' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \

こんな感じでusernameとpassword入れれば音声ファイルが取れる。
textはurlエンコードされてます。
パラメータ等は資料の通りなのであとで整理します。

**Comment by shinji19** [comment]
swiftに組み込んでみます

**Comment by shinji19** [comment]
slack通知テスト
